### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Nishan211775** [projectworlds32/Online-Movie-Ticket-Booking-System-in-php#1]
Can i get a database of this project. I need for my college project

**Comment by projectworldsofficial** [comment]
WhatsApp me +916263056779

**Comment by projectworldsofficial** [comment]
Whatsapp me +916263056779

**Comment by joshuaoyerinde** [comment]
pls what is the admin username and password for online movie ticket system......... pls

**Comment by joshuaoyerinde** [comment]
please can i get the username for admin and password base on online movie ticket booking pls............
i really need it for my project i luv the way u implement ur design
